linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

matrix:
   include:

      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 ARCH=x86 CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=1

      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 ARCH=x86 CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=2

      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6-x86 ARCH=x86 CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=3

      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 ARCH=x86_64 CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=1

      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 ARCH=x86_64 CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=2

      - <<: *linux
        env: CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 ARCH=x86_64 CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=3

      - <<: *osx
        env: CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=1

      - <<: *osx
        env: CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=2

      - <<: *osx
        env: CONAN_TOTAL_PAGES=3 CONAN_CURRENT_PAGE=3

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
